Booklist-MVC/Booklist-MVC/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Booklist_MVC.Models
{
    public class Book
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Author { get; set; }
        public string ISBN { get; set; }

    }
}

Booklist-MVC/Booklist-MVC/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Booklist_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;
using Booklist_MVC.Interfaces;

namespace Booklist_MVC.Controllers
{
    [Authorize]
    public class BooksController : Controller
    {

        private readonly DB _db;
        private readonly IGetAuthorization _getAuthorization;

        [BindProperty]
        public Book Book { get; set; }
        public BooksController(DB db, IGetAuthorization getAuthorization)
        {
            _db = db;
            _getAuthorization = getAuthorization;
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                var token = await _getAuthorization.GetTokenFromIdentityServer();
                var response = await _getAuthorization.GetAuthorizationFromAPI(token);
                if (!response.IsSuccessStatusCode)
                {
                    throw new System.ArgumentException(response.StatusCode.ToString());
                }
                var content = await response.Content.ReadAsStringAsync();
                return View();
            }
            catch
            {
                Response.Redirect("/Account/Logout");
                return Redirect("/");
            }

        }

        public IActionResult Upsert(int? id)
        {
            Book = new Book();
            if (id == null)
            {
                //create book
                return View(Book);
            }
            //update book
            Book = _db.Books.FirstOrDefault(u => u.Id == id);
            if (Book == null)
            {
                return NotFound();
            }
            return View(Book);
        }

        #region APICalls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Books.ToListAsync() });
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var bookFromDB = await _db.Books.FindAsync(id);
            if (bookFromDB == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _db.Books.Remove(bookFromDB);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Delete successful!" });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert()
        {
            if (ModelState.IsValid)
            {
                if (Book.Id == 0)
                {
                    _db.Books.Add(Book);
                }
                else
                {
                    _db.Books.Update(Book);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Book);
        }
        #endregion
    }
}

Booklist-MVC/Booklist-MVC/Views/Books/Index.cshtml
<br />
<div class="container row p-0 m-0 ">
    <div class="col-md-6 col-lg-6 col-6">
        <h2 class="text-info">Book List</h2>
    </div>
    <div class="col-3 offset-3">
        <a asp-action="Upsert" asp-controller="Books" class="btn btn-info form-control text-white">
            Add New Book
        </a>
    </div>
    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-striped table-bordered w-100">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Author</th>
                    <th>ISBN</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tr>
                <td> </td>
            </tr>
        </table>
    </div>
</div>

@section Scripts{
    <script src="~/js/booklist.js?v=1"></script>
}

Booklist-MVC/Booklist-MVC/Views/Books/Upsert.cshtml
@model Booklist_MVC.Models.Book

<br />
<h2 class="text-info">@(Model.Id!=0 ? "Edit" : "Create") Book</h2>
<br />
<div class="container border p-3 ">
    <form method="post" asp-action="Upsert">
        @if (Model.Id != 0)
        {
            <input type="hidden" asp-for="Id" />
        }
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Name"></label>
            </div>
            <div class="col-6">
                <input asp-for="Name" class="form-control " />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Author"></label>
            </div>
            <div class="col-6">
                <input asp-for="Author" class="form-control " />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="ISBN"></label>
            </div>
            <div class="col-6">
                <input asp-for="ISBN" class="form-control " />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-6 col-lg-6 col-12 offset-md-3 offset-lg-3 pb-2">
                <button type="submit" class="btn btn-outline-primary form-control">
                    @(Model.Id!=0 ? "Update" : "Create") Book
                </button>
            </div>
            <div class="col-md-4 col-lg-4 col-12">
                <a asp-action="Index" class="btn btn-danger form-control text-white ">Back to list</a>
            </div>

        </div>
    </form>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}